#!/bin/bash
# .claude/lib/sync_skills.sh
# Monggle v3.5 - 스킬 레지스트리 자동 동기화 (Single Source of Truth)

set -euo pipefail

# 프로젝트 루트 설정
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
COMMANDS_DIR="$PROJECT_ROOT/.claude/commands"
SESSION_DIR="$PROJECT_ROOT/.claude/session"

# 출력 파일
SKILLS_MD="$SESSION_DIR/available_skills.md"
SKILLS_JSON="$SESSION_DIR/available_skills.json"
SKILLS_TXT="$SESSION_DIR/available_skills.txt"
FUZZY_MAP="$SESSION_DIR/fuzzy_map.txt"

# ────────────────────────────────────────────────────────────────────────────────
# 스킬 설명 추출 함수 (파일 상단 주석에서)
# ────────────────────────────────────────────────────────────────────────────────
extract_description() {
    local file="$1"
    local desc=""

    # 첫 10줄에서 설명 추출
    desc=$(head -n 10 "$file" | grep -E "^#.*[=-][ ]+" | head -1 | sed 's/^#[# ]*[=-][ ]*//' | tr -d '\n')

    # 없으면 기본 설명
    if [[ -z "$desc" ]]; then
        desc="No description"
    fi

    # 길이 제한 (80자)
    if [[ ${#desc} -gt 80 ]]; then
        desc="${desc:0:77}..."
    fi

    echo "$desc"
}

# ────────────────────────────────────────────────────────────────────────────────
# 스킬 이름 → 실제 명령 파일 경로 해석 (.sh 우선, 없으면 .py)
# ────────────────────────────────────────────────────────────────────────────────
resolve_skill_file() {
    local skill="$1"
    if [[ -f "$COMMANDS_DIR/$skill.sh" ]]; then
        echo "$COMMANDS_DIR/$skill.sh"
    elif [[ -f "$COMMANDS_DIR/$skill.py" ]]; then
        echo "$COMMANDS_DIR/$skill.py"
    fi
}

# ────────────────────────────────────────────────────────────────────────────────
# JSON 문자열 이스케이프 (백슬래시, 따옴표, 제어문자)
# ────────────────────────────────────────────────────────────────────────────────
json_escape() {
    local s="$1"
    s=${s//\\/\\\\}   # 백슬래시 먼저
    s=${s//\"/\\\"}   # 따옴표
    s=$(printf '%s' "$s" | tr '\t' ' ' | tr -d '\000-\037')  # 탭→공백, 나머지 제어문자 제거
    printf '%s' "$s"
}

# ────────────────────────────────────────────────────────────────────────────────
# 메인: 스킬 스캔 및 레지스트리 생성
# ────────────────────────────────────────────────────────────────────────────────
main() {
    echo "🔄 [SKILL SYNC] 스킬 레지스트리 동기화 시작..."

    # 세션 디렉토리 확인
    mkdir -p "$SESSION_DIR"

    # 1. 스킬 파일 스캔 (정렬된 유니크 목록)
    local skills=()
    local seen=" "
    while IFS= read -r -d '' file; do
        # 확장자 제거
        local skill_name=$(basename "$file" | sed 's/\.[^.]*$//')
        # 중복 제거 (foo.sh + foo.py → foo 한 번만)
        case "$seen" in
            *" $skill_name "*) continue ;;
        esac
        seen="$seen$skill_name "
        skills+=("$skill_name")
    done < <(find "$COMMANDS_DIR" -maxdepth 1 -type f \( -name "*.sh" -o -name "*.py" \) -print0 | sort -z)

    local skill_count=${#skills[@]}

    # 2. TXT 생성 (공백으로 구분된 목록 - Bash용)
    {
        echo "# Generated by sync_skills.sh - DO NOT EDIT MANUALLY"
        echo "# Last updated: $(date '+%Y-%m-%d %H:%M:%S')"
        echo "# Total skills: $skill_count"
        echo ""
        printf "%s" "${skills[*]}"
    } > "$SKILLS_TXT"

    # 3. JSON 생성 (구조화된 데이터)
    {
        echo "{"
        echo "  \"generated_at\": \"$(date -u '+%Y-%m-%dT%H:%M:%SZ')\","
        echo "  \"total\": $skill_count,"
        echo "  \"skills\": ["
        local first=true
        local json_items=()
        for skill in "${skills[@]:-}"; do
            [[ -z "$skill" ]] && continue
            local skill_file=$(resolve_skill_file "$skill")
            local desc="No description"
            [[ -n "$skill_file" ]] && desc=$(extract_description "$skill_file" 2>/dev/null || echo "No description")
            # desc에서 JSON 이스케이프 (백슬래시/따옴표/제어문자)
            desc=$(json_escape "$desc")
            json_items+=("    {\"name\": \"$skill\", \"desc\": \"$desc\"}")
        done
        local IFS=$'\n'
        printf "%s,\n" "${json_items[@]}" | sed '$ s/,$//' | sed 's/^/  /'
        echo ""
        echo "  ]"
        echo "}"
    } > "$SKILLS_JSON"

    # 4. Markdown 생성 (사용자용)
    {
        echo "# Available Skills"
        echo ""
        echo "**Generated:** $(date '+%Y-%m-%d %H:%M:%S') | **Total:** $skill_count skills"
        echo ""
        echo "---"
        echo ""
        echo "## Quick Reference"
        echo ""
        echo "| Skill | Description |"
        echo "|-------|-------------|"
        for skill in "${skills[@]:-}"; do
            [[ -z "$skill" ]] && continue
            local skill_file=$(resolve_skill_file "$skill")
            local desc="No description"
            [[ -n "$skill_file" ]] && desc=$(extract_description "$skill_file" 2>/dev/null || echo "No description")
            printf "| \`/%s\` | %s |\n" "$skill" "$desc"
        done
        echo ""
        echo "---"
        echo ""
        echo "## Raw List (for Bash scripts)"
        echo ""
        echo '```bash'
        echo 'VALID_SKILLS="'
        printf "%s " "${skills[@]:-}"
        echo '"'
        echo '```'
    } > "$SKILLS_MD"

    # 5. 퍼지 맵 생성 (오타 감지용) - macOS bash 3.x 호환
    {
        echo "# Fuzzy Match Map for agent-pre-check"
        echo "# Format: pattern|target (space-separated pairs)"
        echo "# Generated by sync_skills.sh - DO NOT EDIT MANUALLY"
        echo ""
        echo "# Pairs: pattern1|pattern2 target"
        echo "debugg|debuger|debugging|bug|bugs debug"
        echo "qaa|testt|tests qa"
        echo "git-push|gitpush|commit push-safe"
        echo "doc|documentation|readme|md tech-doc-writer"
        echo "smrat|cmopact|comapct smart-compact"
        echo "code-review|reviewer|review-code code-reviewer"
        echo "architecture|design arch-review"
        echo "planner|plan prd"
        echo "perf|performance|slow bottleneck"
        echo "log|logs|change changelog"
        echo "ver|version bump"
        echo "stat stats"
        echo "hotfix|fix quick"
        echo "lint lint-smart"
        echo "idea|ideas brainstorm"
        echo "checkpoint|save|savep save-point"
        echo "mem|memory mem-check"
        echo "prof|profiling profile"
        echo "trac|tracing trace"
        echo "in|initial|setup init"
        echo "gaurd|guardian git-guardian"
        echo "api|apidocs api-docs"
    } > "$FUZZY_MAP"

    echo "✅ [SUCCESS] 스킬 레지스트리 생성 완료!"
    echo "   - $SKILLS_TXT (Bash용)"
    echo "   - $SKILLS_JSON (API용)"
    echo "   - $SKILLS_MD (문서용)"
    echo "   - $FUZZY_MAP (오타 교정용)"
    echo "   - 총 ${#skills[@]:-0}개 스킬 등록됨"

    # 5. 권한 설정
    chmod +x "$SKILLS_TXT" 2>/dev/null || true
}

# 실행
main "$@"
